"""
ITAU
EXTRATO DE CONTA CORRENTE
Layout de Arquivos – CNAB240 – Versão 5.0
"""

from datetime import datetime

from pyFixedFlatFile.cnabs.base import CNAB240

Itau = CNAB240(start=8, stop=9, identifier_name='tipo_registro')

# REGISTRO HEADER DE ARQUIVO - TAMANHO DO REGISTRO = 240 Bytes

format_date_8 = lambda d: datetime.strptime(d, '%d%m%Y')
format_value = lambda value: value[:16] + '.' + value[16:]

Itau.eq('0')
(Itau
    .codigo_banco(3, tp=int)
    .codigo_lote(4, tp=int)
    .tipo_registro(1)
    .vazio1(9)
    .tipo_inscricao(1)
    .numero_inscricao(14, tp=int)
    .vazio2(15)
    .codigo_convenio(5)
    .zeros1(1, tp=int)
    .codigo_agencia(4, tp=int)
    .digito_verificador_agencia(1)
    .zeros(7, tp=int)
    .numero_conta(5, tp=int)
    .vazio3(1)
    .digito_verificador_conta_agencia(1)
    .nome_empresa(30)
    .nome_banco(30)
    .vazio4(10)
    .codigo_retorno(1)
    .data_geracao_arquivo(8, fmt_r=format_date_8, fmt_w=lambda d: format(d, '%d%m%Y'))
    .hora_geracao_arquivo(6, fmt_r=lambda date, data:  datetime.strptime(data['data_geracao_arquivo'].strftime('%d%m%Y') + ' ' + date, '%d%m%Y %H%M%S'), fmt_w=lambda d: format(d, '%H%M%S'))
    .sequencia(6, tp=int)
    .layout(3)
    .zeros2(5, tp=int)
    .reservado(5)
    .vazio5(49))

# REGISTRO HEADER LOTE - TAMANHO DO REGISTRO = 240 Bytes
Itau.eq('1')
(Itau
    .codigo_banco(3, tp=int)
    .codigo_lote(4, tp=int)
    .tipo_registro(1)
    .tipo_operacao(1)
    .tipo_servico(2, tp=int)
    .forma_lancamento(2, tp=int)
    .layout(3)
    .vazio1(1)
    .tipo_inscricao(1)
    .numero_inscricao(14, tp=int)
    .tipo_conta(4)
    .vazio2(11)
    .codigo_convenio(5)
    .zeros1(1, tp=int)
    .codigo_agencia(4, tp=int)
    .digito_verificador_agencia(1)
    .zeros(7, tp=int)
    .numero_conta(5, tp=int)
    .vazio3(1)
    .digito_verificador_conta_agencia(1)
    .nome_empresa(30)
    .vazio4(40)
    .data_inicial(8, fmt_r=format_date_8, fmt_w=lambda d: format(d, '%d%m%Y'))
    .valor_inicial(18, fmt_r=format_value, tp=float)
    .situacao_inicial(1)
    .status_inicial(1)
    .tipo_moeda(3)
    .sequencia_extrato(5, tp=int)
    .vazio5(62))

# REGISTRO SEGMENTO E - TAMANHO DO REGISTRO = 240 Bytes
Itau.eq('3')
(Itau
    .codigo_banco(3, tp=int)
    .codigo_lote(4, tp=int)
    .tipo_registro(1)
    .numero_registro(5, tp=int)
    .segmento(1)
    .lancamento1(1)
    .vazio1(2)
    .tipo_inscricao(1)
    .numero_inscricao(14)
    .vazio2(15)
    .codigo_convenio(5)
    .zeros1(1)
    .codigo_agencia(4)
    .digito_verificador_agencia(1)
    .zeros(7)
    .numero_conta(5)
    .vazio3(1)
    .digito_verificador_conta_agencia(1)
    .nome_empresa(30)
    .reservado(6)
    .natureza(3)
    .tipo_complemento(2)
    .banco_origem(3)
    .agencia_origem(5)
    .agencia_conta_origem(12)
    .cpmf(1)
    .data_contabil(8, fmt_r=lambda d: datetime.strptime(d, '%d%m%Y') if d else '', fmt_w=lambda d: format(d, '%d%m%Y') if d else '')
    .data_lancamento(8, fmt_r=lambda d: datetime.strptime(d, '%d%m%Y') if d else '', fmt_w=lambda d: format(d, '%d%m%Y') if d else '')
    .valor_lancamento(18, fmt_r=format_value, tp=float)
    .lancamento2(1)
    .categoria(3)
    .codigo_lancamento(4)
    .historico(25)
    .vazio4(33)
    .numero_documento(6))


# REGISTRO TRAILER DE LOTE - TAMANHO DO REGISTRO = 240 Bytes
Itau.eq('5')
(Itau
    .codigo_banco(3, tp=int)
    .codigo_lote(4, tp=int)
    .tipo_registro(1)
    .vazio1(9)
    .tipo_inscricao(1)
    .numero_inscricao(14, tp=int)
    .vazio2(15)
    .codigo_convenio(5)
    .zeros1(1, tp=int)
    .codigo_agencia(4, tp=int)
    .digito_verificador_agencia(1)
    .zeros(7, tp=int)
    .numero_conta(5, tp=int)
    .vazio3(1)
    .digito_verificador_conta_agencia(1)
    .vazio4(16)
    .bloqueado(18, fmt_r=format_value, tp=float)
    .limite(18, fmt_r=format_value, tp=float)
    .saldo_bloqueado(18, fmt_r=format_value, tp=float)
    .data_final(8, fmt_r=format_date_8, fmt_w=lambda d: format(d, '%d%m%Y'))
    .saldo_final(18, fmt_r=format_value, tp=float)
    .situacao(1)
    .status(1)
    .total_registros(6, tp=int)
    .total_valor_debito(18, fmt_r=format_value, tp=float)
    .total_valor_credito(18, fmt_r=format_value, tp=float)
    .totais_valores_nao_contabeis(18, fmt_r=format_value, tp=float)
    .vazio5(10))

#REGISTRO TRAILER DE ARQUIVO - TAMANHO DO REGISTRO = 240 Bytes
Itau.eq('9')
(Itau
    .codigo_banco(3, tp=int)
    .codigo_lote(4)
    .tipo_registro(1)
    .vazio1(9)
    .total_quantidade_lotes(6, tp=int)
    .total_quantidade_registros(6, tp=int)
    .total_contas_conciliadas(6, tp=int)
    .vazio2(205))
